---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-openmcp-cloud-v1alpha1-managedcontrolplane
  failurePolicy: Fail
  name: vmanagedcontrolplane.kb.io
  rules:
  - apiGroups:
    - core.openmcp.cloud
    apiVersions:
    - v1alpha1
    operations:
    - DELETE
    resources:
    - managedcontrolplanes
  sideEffects: None
