#!/bin/bash

set -euo pipefail
PROJECT_ROOT="$(realpath $(dirname $0)/..)"

go_version="$(cat "$PROJECT_ROOT/go.mod" | grep -E 'go ([[:digit:]]\.?)+')" # returns something like 'go 1.2.3 // comment'
go_version=${go_version%%//*} # remove potential comment at end of line
go_version=$(sed -r 's@^[[:blank:]]+|[[:blank:]]+$@@g' <<< $go_version) # remove leading and trailing whitespace
go_version=${go_version#'go '} # remove 'go ' prefix

export GOPRIVATE=github.tools.sap

if ! which go 1>/dev/null; then
  echo "> Installing go $go_version ..."
  
  arch=$(uname -m)
  if [[ "$arch" == "x86_64" ]]; then
    arch="amd64"
  fi
  os=$(uname | tr '[:upper:]' '[:lower:]')

  curl -sfL https://go.dev/dl/go${go_version}.${os}-${arch}.tar.gz --output /tmp/go.tar.gz
  tar -C /usr/local -xzf /tmp/go.tar.gz
  export PATH=$PATH:/usr/local/go/bin
fi
