//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServer) DeepCopyInto(out *APIServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServer.
func (in *APIServer) DeepCopy() *APIServer {
	if in == nil {
		return nil
	}
	out := new(APIServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerAccess) DeepCopyInto(out *APIServerAccess) {
	*out = *in
	if in.CreationTimestamp != nil {
		in, out := &in.CreationTimestamp, &out.CreationTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ExpirationTimestamp != nil {
		in, out := &in.ExpirationTimestamp, &out.ExpirationTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerAccess.
func (in *APIServerAccess) DeepCopy() *APIServerAccess {
	if in == nil {
		return nil
	}
	out := new(APIServerAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerConfiguration) DeepCopyInto(out *APIServerConfiguration) {
	*out = *in
	if in.GardenerConfig != nil {
		in, out := &in.GardenerConfig, &out.GardenerConfig
		*out = new(GardenerConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerConfiguration.
func (in *APIServerConfiguration) DeepCopy() *APIServerConfiguration {
	if in == nil {
		return nil
	}
	out := new(APIServerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerInternalConfiguration) DeepCopyInto(out *APIServerInternalConfiguration) {
	*out = *in
	if in.GardenerConfig != nil {
		in, out := &in.GardenerConfig, &out.GardenerConfig
		*out = new(GardenerInternalConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerInternalConfiguration.
func (in *APIServerInternalConfiguration) DeepCopy() *APIServerInternalConfiguration {
	if in == nil {
		return nil
	}
	out := new(APIServerInternalConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerList) DeepCopyInto(out *APIServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerList.
func (in *APIServerList) DeepCopy() *APIServerList {
	if in == nil {
		return nil
	}
	out := new(APIServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerSpec) DeepCopyInto(out *APIServerSpec) {
	*out = *in
	in.APIServerConfiguration.DeepCopyInto(&out.APIServerConfiguration)
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(APIServerInternalConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.DesiredRegion != nil {
		in, out := &in.DesiredRegion, &out.DesiredRegion
		*out = new(RegionSpecification)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerSpec.
func (in *APIServerSpec) DeepCopy() *APIServerSpec {
	if in == nil {
		return nil
	}
	out := new(APIServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerStatus) DeepCopyInto(out *APIServerStatus) {
	*out = *in
	in.CommonComponentStatus.DeepCopyInto(&out.CommonComponentStatus)
	if in.ExternalAPIServerStatus != nil {
		in, out := &in.ExternalAPIServerStatus, &out.ExternalAPIServerStatus
		*out = new(ExternalAPIServerStatus)
		**out = **in
	}
	if in.AdminAccess != nil {
		in, out := &in.AdminAccess, &out.AdminAccess
		*out = new(APIServerAccess)
		(*in).DeepCopyInto(*out)
	}
	if in.GardenerStatus != nil {
		in, out := &in.GardenerStatus, &out.GardenerStatus
		*out = new(GardenerStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerStatus.
func (in *APIServerStatus) DeepCopy() *APIServerStatus {
	if in == nil {
		return nil
	}
	out := new(APIServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogConfig) DeepCopyInto(out *AuditLogConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
	out.PolicyRef = in.PolicyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogConfig.
func (in *AuditLogConfig) DeepCopy() *AuditLogConfig {
	if in == nil {
		return nil
	}
	out := new(AuditLogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication) DeepCopyInto(out *Authentication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication.
func (in *Authentication) DeepCopy() *Authentication {
	if in == nil {
		return nil
	}
	out := new(Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Authentication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationConfiguration) DeepCopyInto(out *AuthenticationConfiguration) {
	*out = *in
	if in.EnableSystemIdentityProvider != nil {
		in, out := &in.EnableSystemIdentityProvider, &out.EnableSystemIdentityProvider
		*out = new(bool)
		**out = **in
	}
	if in.IdentityProviders != nil {
		in, out := &in.IdentityProviders, &out.IdentityProviders
		*out = make([]IdentityProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationConfiguration.
func (in *AuthenticationConfiguration) DeepCopy() *AuthenticationConfiguration {
	if in == nil {
		return nil
	}
	out := new(AuthenticationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationList) DeepCopyInto(out *AuthenticationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Authentication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationList.
func (in *AuthenticationList) DeepCopy() *AuthenticationList {
	if in == nil {
		return nil
	}
	out := new(AuthenticationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthenticationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationSpec) DeepCopyInto(out *AuthenticationSpec) {
	*out = *in
	in.AuthenticationConfiguration.DeepCopyInto(&out.AuthenticationConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationSpec.
func (in *AuthenticationSpec) DeepCopy() *AuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(AuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationStatus) DeepCopyInto(out *AuthenticationStatus) {
	*out = *in
	in.CommonComponentStatus.DeepCopyInto(&out.CommonComponentStatus)
	if in.ExternalAuthenticationStatus != nil {
		in, out := &in.ExternalAuthenticationStatus, &out.ExternalAuthenticationStatus
		*out = new(ExternalAuthenticationStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationStatus.
func (in *AuthenticationStatus) DeepCopy() *AuthenticationStatus {
	if in == nil {
		return nil
	}
	out := new(AuthenticationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authorization) DeepCopyInto(out *Authorization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authorization.
func (in *Authorization) DeepCopy() *Authorization {
	if in == nil {
		return nil
	}
	out := new(Authorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Authorization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationConfiguration) DeepCopyInto(out *AuthorizationConfiguration) {
	*out = *in
	if in.RoleBindings != nil {
		in, out := &in.RoleBindings, &out.RoleBindings
		*out = make([]RoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationConfiguration.
func (in *AuthorizationConfiguration) DeepCopy() *AuthorizationConfiguration {
	if in == nil {
		return nil
	}
	out := new(AuthorizationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationList) DeepCopyInto(out *AuthorizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Authorization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationList.
func (in *AuthorizationList) DeepCopy() *AuthorizationList {
	if in == nil {
		return nil
	}
	out := new(AuthorizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationSpec) DeepCopyInto(out *AuthorizationSpec) {
	*out = *in
	in.AuthorizationConfiguration.DeepCopyInto(&out.AuthorizationConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationSpec.
func (in *AuthorizationSpec) DeepCopy() *AuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationStatus) DeepCopyInto(out *AuthorizationStatus) {
	*out = *in
	in.CommonComponentStatus.DeepCopyInto(&out.CommonComponentStatus)
	if in.ExternalAuthorizationStatus != nil {
		in, out := &in.ExternalAuthorizationStatus, &out.ExternalAuthorizationStatus
		*out = new(ExternalAuthorizationStatus)
		**out = **in
	}
	if in.UserNamespaces != nil {
		in, out := &in.UserNamespaces, &out.UserNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationStatus.
func (in *AuthorizationStatus) DeepCopy() *AuthorizationStatus {
	if in == nil {
		return nil
	}
	out := new(AuthorizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BTPServiceOperatorConfig) DeepCopyInto(out *BTPServiceOperatorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BTPServiceOperatorConfig.
func (in *BTPServiceOperatorConfig) DeepCopy() *BTPServiceOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(BTPServiceOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientAuthenticationConfig) DeepCopyInto(out *ClientAuthenticationConfig) {
	*out = *in
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(LocalSecretReference)
		**out = **in
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]SingleOrMultiStringValue, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientAuthenticationConfig.
func (in *ClientAuthenticationConfig) DeepCopy() *ClientAuthenticationConfig {
	if in == nil {
		return nil
	}
	out := new(ClientAuthenticationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudOrchestrator) DeepCopyInto(out *CloudOrchestrator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudOrchestrator.
func (in *CloudOrchestrator) DeepCopy() *CloudOrchestrator {
	if in == nil {
		return nil
	}
	out := new(CloudOrchestrator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudOrchestrator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudOrchestratorConfiguration) DeepCopyInto(out *CloudOrchestratorConfiguration) {
	*out = *in
	if in.Crossplane != nil {
		in, out := &in.Crossplane, &out.Crossplane
		*out = new(CrossplaneConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BTPServiceOperator != nil {
		in, out := &in.BTPServiceOperator, &out.BTPServiceOperator
		*out = new(BTPServiceOperatorConfig)
		**out = **in
	}
	if in.ExternalSecretsOperator != nil {
		in, out := &in.ExternalSecretsOperator, &out.ExternalSecretsOperator
		*out = new(ExternalSecretsOperatorConfig)
		**out = **in
	}
	if in.Kyverno != nil {
		in, out := &in.Kyverno, &out.Kyverno
		*out = new(KyvernoConfig)
		**out = **in
	}
	if in.Flux != nil {
		in, out := &in.Flux, &out.Flux
		*out = new(FluxConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudOrchestratorConfiguration.
func (in *CloudOrchestratorConfiguration) DeepCopy() *CloudOrchestratorConfiguration {
	if in == nil {
		return nil
	}
	out := new(CloudOrchestratorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudOrchestratorList) DeepCopyInto(out *CloudOrchestratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudOrchestrator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudOrchestratorList.
func (in *CloudOrchestratorList) DeepCopy() *CloudOrchestratorList {
	if in == nil {
		return nil
	}
	out := new(CloudOrchestratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudOrchestratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudOrchestratorSpec) DeepCopyInto(out *CloudOrchestratorSpec) {
	*out = *in
	in.CloudOrchestratorConfiguration.DeepCopyInto(&out.CloudOrchestratorConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudOrchestratorSpec.
func (in *CloudOrchestratorSpec) DeepCopy() *CloudOrchestratorSpec {
	if in == nil {
		return nil
	}
	out := new(CloudOrchestratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudOrchestratorStatus) DeepCopyInto(out *CloudOrchestratorStatus) {
	*out = *in
	in.CommonComponentStatus.DeepCopyInto(&out.CommonComponentStatus)
	if in.ExternalCloudOrchestratorStatus != nil {
		in, out := &in.ExternalCloudOrchestratorStatus, &out.ExternalCloudOrchestratorStatus
		*out = new(ExternalCloudOrchestratorStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudOrchestratorStatus.
func (in *CloudOrchestratorStatus) DeepCopy() *CloudOrchestratorStatus {
	if in == nil {
		return nil
	}
	out := new(CloudOrchestratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAdmin) DeepCopyInto(out *ClusterAdmin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAdmin.
func (in *ClusterAdmin) DeepCopy() *ClusterAdmin {
	if in == nil {
		return nil
	}
	out := new(ClusterAdmin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAdmin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAdminList) DeepCopyInto(out *ClusterAdminList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterAdmin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAdminList.
func (in *ClusterAdminList) DeepCopy() *ClusterAdminList {
	if in == nil {
		return nil
	}
	out := new(ClusterAdminList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAdminList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAdminSpec) DeepCopyInto(out *ClusterAdminSpec) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]Subject, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAdminSpec.
func (in *ClusterAdminSpec) DeepCopy() *ClusterAdminSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAdminSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAdminStatus) DeepCopyInto(out *ClusterAdminStatus) {
	*out = *in
	if in.Activated != nil {
		in, out := &in.Activated, &out.Activated
		*out = (*in).DeepCopy()
	}
	if in.Expiration != nil {
		in, out := &in.Expiration, &out.Expiration
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAdminStatus.
func (in *ClusterAdminStatus) DeepCopy() *ClusterAdminStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterAdminStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonComponentStatus) DeepCopyInto(out *CommonComponentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(ComponentConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ObservedGenerations = in.ObservedGenerations
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonComponentStatus.
func (in *CommonComponentStatus) DeepCopy() *CommonComponentStatus {
	if in == nil {
		return nil
	}
	out := new(CommonComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonConfig) DeepCopyInto(out *CommonConfig) {
	*out = *in
	if in.DesiredRegion != nil {
		in, out := &in.DesiredRegion, &out.DesiredRegion
		*out = new(RegionSpecification)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonConfig.
func (in *CommonConfig) DeepCopy() *CommonConfig {
	if in == nil {
		return nil
	}
	out := new(CommonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentCondition) DeepCopyInto(out *ComponentCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentCondition.
func (in *ComponentCondition) DeepCopy() *ComponentCondition {
	if in == nil {
		return nil
	}
	out := new(ComponentCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ComponentConditionList) DeepCopyInto(out *ComponentConditionList) {
	{
		in := &in
		*out = make(ComponentConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentConditionList.
func (in ComponentConditionList) DeepCopy() ComponentConditionList {
	if in == nil {
		return nil
	}
	out := new(ComponentConditionList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneConfig) DeepCopyInto(out *CrossplaneConfig) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]*CrossplaneProviderConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CrossplaneProviderConfig)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneConfig.
func (in *CrossplaneConfig) DeepCopy() *CrossplaneConfig {
	if in == nil {
		return nil
	}
	out := new(CrossplaneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneProviderConfig) DeepCopyInto(out *CrossplaneProviderConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneProviderConfig.
func (in *CrossplaneProviderConfig) DeepCopy() *CrossplaneProviderConfig {
	if in == nil {
		return nil
	}
	out := new(CrossplaneProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionConfig) DeepCopyInto(out *EncryptionConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionConfig.
func (in *EncryptionConfig) DeepCopy() *EncryptionConfig {
	if in == nil {
		return nil
	}
	out := new(EncryptionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAPIServerStatus) DeepCopyInto(out *ExternalAPIServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAPIServerStatus.
func (in *ExternalAPIServerStatus) DeepCopy() *ExternalAPIServerStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalAPIServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthenticationStatus) DeepCopyInto(out *ExternalAuthenticationStatus) {
	*out = *in
	if in.UserAccess != nil {
		in, out := &in.UserAccess, &out.UserAccess
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthenticationStatus.
func (in *ExternalAuthenticationStatus) DeepCopy() *ExternalAuthenticationStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthenticationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthorizationStatus) DeepCopyInto(out *ExternalAuthorizationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthorizationStatus.
func (in *ExternalAuthorizationStatus) DeepCopy() *ExternalAuthorizationStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthorizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalCloudOrchestratorStatus) DeepCopyInto(out *ExternalCloudOrchestratorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalCloudOrchestratorStatus.
func (in *ExternalCloudOrchestratorStatus) DeepCopy() *ExternalCloudOrchestratorStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalCloudOrchestratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalLandscaperStatus) DeepCopyInto(out *ExternalLandscaperStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalLandscaperStatus.
func (in *ExternalLandscaperStatus) DeepCopy() *ExternalLandscaperStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalLandscaperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretsOperatorConfig) DeepCopyInto(out *ExternalSecretsOperatorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretsOperatorConfig.
func (in *ExternalSecretsOperatorConfig) DeepCopy() *ExternalSecretsOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretsOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxConfig) DeepCopyInto(out *FluxConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxConfig.
func (in *FluxConfig) DeepCopy() *FluxConfig {
	if in == nil {
		return nil
	}
	out := new(FluxConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenerConfiguration) DeepCopyInto(out *GardenerConfiguration) {
	*out = *in
	if in.HighAvailabilityConfig != nil {
		in, out := &in.HighAvailabilityConfig, &out.HighAvailabilityConfig
		*out = new(HighAvailabilityConfig)
		**out = **in
	}
	if in.AuditLog != nil {
		in, out := &in.AuditLog, &out.AuditLog
		*out = new(AuditLogConfig)
		**out = **in
	}
	if in.EncryptionConfig != nil {
		in, out := &in.EncryptionConfig, &out.EncryptionConfig
		*out = new(EncryptionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenerConfiguration.
func (in *GardenerConfiguration) DeepCopy() *GardenerConfiguration {
	if in == nil {
		return nil
	}
	out := new(GardenerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenerInternalConfiguration) DeepCopyInto(out *GardenerInternalConfiguration) {
	*out = *in
	if in.ShootOverwrite != nil {
		in, out := &in.ShootOverwrite, &out.ShootOverwrite
		*out = new(NamespacedObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenerInternalConfiguration.
func (in *GardenerInternalConfiguration) DeepCopy() *GardenerInternalConfiguration {
	if in == nil {
		return nil
	}
	out := new(GardenerInternalConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenerStatus) DeepCopyInto(out *GardenerStatus) {
	*out = *in
	if in.Shoot != nil {
		in, out := &in.Shoot, &out.Shoot
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenerStatus.
func (in *GardenerStatus) DeepCopy() *GardenerStatus {
	if in == nil {
		return nil
	}
	out := new(GardenerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HighAvailabilityConfig) DeepCopyInto(out *HighAvailabilityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HighAvailabilityConfig.
func (in *HighAvailabilityConfig) DeepCopy() *HighAvailabilityConfig {
	if in == nil {
		return nil
	}
	out := new(HighAvailabilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProvider) DeepCopyInto(out *IdentityProvider) {
	*out = *in
	if in.SigningAlgs != nil {
		in, out := &in.SigningAlgs, &out.SigningAlgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredClaims != nil {
		in, out := &in.RequiredClaims, &out.RequiredClaims
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ClientConfig.DeepCopyInto(&out.ClientConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProvider.
func (in *IdentityProvider) DeepCopy() *IdentityProvider {
	if in == nil {
		return nil
	}
	out := new(IdentityProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalCommonConfig) DeepCopyInto(out *InternalCommonConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalCommonConfig.
func (in *InternalCommonConfig) DeepCopy() *InternalCommonConfig {
	if in == nil {
		return nil
	}
	out := new(InternalCommonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalConfiguration) DeepCopyInto(out *InternalConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalConfiguration.
func (in *InternalConfiguration) DeepCopy() *InternalConfiguration {
	if in == nil {
		return nil
	}
	out := new(InternalConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InternalConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalConfigurationComponents) DeepCopyInto(out *InternalConfigurationComponents) {
	*out = *in
	if in.APIServer != nil {
		in, out := &in.APIServer, &out.APIServer
		*out = new(APIServerInternalConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalConfigurationComponents.
func (in *InternalConfigurationComponents) DeepCopy() *InternalConfigurationComponents {
	if in == nil {
		return nil
	}
	out := new(InternalConfigurationComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalConfigurationList) DeepCopyInto(out *InternalConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InternalConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalConfigurationList.
func (in *InternalConfigurationList) DeepCopy() *InternalConfigurationList {
	if in == nil {
		return nil
	}
	out := new(InternalConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InternalConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalConfigurationSpec) DeepCopyInto(out *InternalConfigurationSpec) {
	*out = *in
	if in.InternalCommonConfig != nil {
		in, out := &in.InternalCommonConfig, &out.InternalCommonConfig
		*out = new(InternalCommonConfig)
		**out = **in
	}
	in.Components.DeepCopyInto(&out.Components)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalConfigurationSpec.
func (in *InternalConfigurationSpec) DeepCopy() *InternalConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(InternalConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KyvernoConfig) DeepCopyInto(out *KyvernoConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KyvernoConfig.
func (in *KyvernoConfig) DeepCopy() *KyvernoConfig {
	if in == nil {
		return nil
	}
	out := new(KyvernoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Landscaper) DeepCopyInto(out *Landscaper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Landscaper.
func (in *Landscaper) DeepCopy() *Landscaper {
	if in == nil {
		return nil
	}
	out := new(Landscaper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Landscaper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperConfiguration) DeepCopyInto(out *LandscaperConfiguration) {
	*out = *in
	if in.Deployers != nil {
		in, out := &in.Deployers, &out.Deployers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperConfiguration.
func (in *LandscaperConfiguration) DeepCopy() *LandscaperConfiguration {
	if in == nil {
		return nil
	}
	out := new(LandscaperConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperDeploymentInfo) DeepCopyInto(out *LandscaperDeploymentInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperDeploymentInfo.
func (in *LandscaperDeploymentInfo) DeepCopy() *LandscaperDeploymentInfo {
	if in == nil {
		return nil
	}
	out := new(LandscaperDeploymentInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperList) DeepCopyInto(out *LandscaperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Landscaper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperList.
func (in *LandscaperList) DeepCopy() *LandscaperList {
	if in == nil {
		return nil
	}
	out := new(LandscaperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LandscaperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperSpec) DeepCopyInto(out *LandscaperSpec) {
	*out = *in
	in.LandscaperConfiguration.DeepCopyInto(&out.LandscaperConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperSpec.
func (in *LandscaperSpec) DeepCopy() *LandscaperSpec {
	if in == nil {
		return nil
	}
	out := new(LandscaperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscaperStatus) DeepCopyInto(out *LandscaperStatus) {
	*out = *in
	in.CommonComponentStatus.DeepCopyInto(&out.CommonComponentStatus)
	if in.ExternalLandscaperStatus != nil {
		in, out := &in.ExternalLandscaperStatus, &out.ExternalLandscaperStatus
		*out = new(ExternalLandscaperStatus)
		**out = **in
	}
	if in.LandscaperDeploymentInfo != nil {
		in, out := &in.LandscaperDeploymentInfo, &out.LandscaperDeploymentInfo
		*out = new(LandscaperDeploymentInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscaperStatus.
func (in *LandscaperStatus) DeepCopy() *LandscaperStatus {
	if in == nil {
		return nil
	}
	out := new(LandscaperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretReference.
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedComponent) DeepCopyInto(out *ManagedComponent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedComponent.
func (in *ManagedComponent) DeepCopy() *ManagedComponent {
	if in == nil {
		return nil
	}
	out := new(ManagedComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedComponent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedComponentList) DeepCopyInto(out *ManagedComponentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedComponentList.
func (in *ManagedComponentList) DeepCopy() *ManagedComponentList {
	if in == nil {
		return nil
	}
	out := new(ManagedComponentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedComponentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedComponentSpec) DeepCopyInto(out *ManagedComponentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedComponentSpec.
func (in *ManagedComponentSpec) DeepCopy() *ManagedComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedComponentStatus) DeepCopyInto(out *ManagedComponentStatus) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedComponentStatus.
func (in *ManagedComponentStatus) DeepCopy() *ManagedComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlane) DeepCopyInto(out *ManagedControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlane.
func (in *ManagedControlPlane) DeepCopy() *ManagedControlPlane {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneComponentCondition) DeepCopyInto(out *ManagedControlPlaneComponentCondition) {
	*out = *in
	in.ComponentCondition.DeepCopyInto(&out.ComponentCondition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneComponentCondition.
func (in *ManagedControlPlaneComponentCondition) DeepCopy() *ManagedControlPlaneComponentCondition {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneComponentCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneComponents) DeepCopyInto(out *ManagedControlPlaneComponents) {
	*out = *in
	if in.APIServer != nil {
		in, out := &in.APIServer, &out.APIServer
		*out = new(APIServerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Landscaper != nil {
		in, out := &in.Landscaper, &out.Landscaper
		*out = new(LandscaperConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.CloudOrchestratorConfiguration.DeepCopyInto(&out.CloudOrchestratorConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneComponents.
func (in *ManagedControlPlaneComponents) DeepCopy() *ManagedControlPlaneComponents {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneComponentsStatus) DeepCopyInto(out *ManagedControlPlaneComponentsStatus) {
	*out = *in
	if in.APIServer != nil {
		in, out := &in.APIServer, &out.APIServer
		*out = new(ExternalAPIServerStatus)
		**out = **in
	}
	if in.Landscaper != nil {
		in, out := &in.Landscaper, &out.Landscaper
		*out = new(ExternalLandscaperStatus)
		**out = **in
	}
	if in.CloudOrchestrator != nil {
		in, out := &in.CloudOrchestrator, &out.CloudOrchestrator
		*out = new(ExternalCloudOrchestratorStatus)
		**out = **in
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(ExternalAuthenticationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = new(ExternalAuthorizationStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneComponentsStatus.
func (in *ManagedControlPlaneComponentsStatus) DeepCopy() *ManagedControlPlaneComponentsStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneComponentsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneList) DeepCopyInto(out *ManagedControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneList.
func (in *ManagedControlPlaneList) DeepCopy() *ManagedControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneMetaStatus) DeepCopyInto(out *ManagedControlPlaneMetaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneMetaStatus.
func (in *ManagedControlPlaneMetaStatus) DeepCopy() *ManagedControlPlaneMetaStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneMetaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneSpec) DeepCopyInto(out *ManagedControlPlaneSpec) {
	*out = *in
	if in.DisabledComponents != nil {
		in, out := &in.DisabledComponents, &out.DisabledComponents
		*out = make([]ComponentType, len(*in))
		copy(*out, *in)
	}
	if in.CommonConfig != nil {
		in, out := &in.CommonConfig, &out.CommonConfig
		*out = new(CommonConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthenticationConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = new(AuthorizationConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.Components.DeepCopyInto(&out.Components)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneSpec.
func (in *ManagedControlPlaneSpec) DeepCopy() *ManagedControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlaneStatus) DeepCopyInto(out *ManagedControlPlaneStatus) {
	*out = *in
	out.ManagedControlPlaneMetaStatus = in.ManagedControlPlaneMetaStatus
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ManagedControlPlaneComponentCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Components.DeepCopyInto(&out.Components)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlaneStatus.
func (in *ManagedControlPlaneStatus) DeepCopy() *ManagedControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectReference) DeepCopyInto(out *NamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference.
func (in *NamespacedObjectReference) DeepCopy() *NamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedGenerations) DeepCopyInto(out *ObservedGenerations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedGenerations.
func (in *ObservedGenerations) DeepCopy() *ObservedGenerations {
	if in == nil {
		return nil
	}
	out := new(ObservedGenerations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSpecification) DeepCopyInto(out *RegionSpecification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSpecification.
func (in *RegionSpecification) DeepCopy() *RegionSpecification {
	if in == nil {
		return nil
	}
	out := new(RegionSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleBinding) DeepCopyInto(out *RoleBinding) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]Subject, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleBinding.
func (in *RoleBinding) DeepCopy() *RoleBinding {
	if in == nil {
		return nil
	}
	out := new(RoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
	out.NamespacedObjectReference = in.NamespacedObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleOrMultiStringValue) DeepCopyInto(out *SingleOrMultiStringValue) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleOrMultiStringValue.
func (in *SingleOrMultiStringValue) DeepCopy() *SingleOrMultiStringValue {
	if in == nil {
		return nil
	}
	out := new(SingleOrMultiStringValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subject) DeepCopyInto(out *Subject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subject.
func (in *Subject) DeepCopy() *Subject {
	if in == nil {
		return nil
	}
	out := new(Subject)
	in.DeepCopyInto(out)
	return out
}
