---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-operator-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    architecture:
      {{- if and .Values.architecture .Values.architecture.immutability }}
      immutability:
      {{- .Values.architecture.immutability | toYaml | nindent 8 }}
      {{- end }}
      {{- if and .Values.apiserver .Values.apiserver.architecture }}
      apiserver:
        version: {{ .Values.apiserver.architecture.version | default "v1" }}
        allowOverride: {{ .Values.apiserver.architecture.allowOverride | default false }}
      {{- end }}
      landscaper:
        version: {{ .Values.landscaper.architecture.version | default "v1" }}
        allowOverride: {{ .Values.landscaper.architecture.allowOverride | default false }}
      {{- end }}
