{{- if has "authentication" ( include "mcp-operator.activeControllers" .Values | fromYamlArray ) }}
apiVersion: v1
kind: Secret
metadata:
  name: authentication-provider-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-operator.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.authentication.config | toYaml | b64enc }}
{{- end }}
