{{- if .Values.clusters }}
{{- range $cname, $cvalues := .Values.clusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cname }}-cluster
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "mcp-operator.labels" $ | nindent 4 }}
data:
  {{- range $k, $v := $cvalues }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
