{{- if has "cloudorchestrator" ( include "mcp-operator.activeControllers" .Values | fromYamlArray ) }}
{{- if .Values.cloudOrchestrator.clusters }}
{{- range $cname, $cvalues := .Values.cloudOrchestrator.clusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudorchestrator-{{ $cname }}-cluster
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "mcp-operator.labels" $ | nindent 4 }}
data:
  {{- range $k, $v := $cvalues }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
