{{- if has "apiserver" ( include "mcp-operator.activeControllers" .Values | fromYamlArray ) }}
apiVersion: v1
kind: Secret
metadata:
  name: apiserver-provider-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-operator.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.apiserver.config | toYaml | b64enc }}
{{- end }}
