{{- if has "authorization" ( include "mcp-operator.activeControllers" .Values | fromYamlArray ) }}
apiVersion: v1
kind: Secret
metadata:
  name: authorization-provider-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-operator.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.authorization.config | toYaml | b64enc }}
{{- end }}
